# REST
# ทุกค่า input อ่านจากไฟล์ .env

## 1. Admin Section

### 1.1 Login (Admin)

### 1.1 Login (Admin)

POST http://localhost:8080/admin/login
Content-Type: application/json

{
    "email": "{{$dotenv ADMIN_EMAIL}}",
    "password": "{{$dotenv STRAPI_ADMIN_PASSWORD}}",
    "rememberMe": true
}

### 1.2 Register (Admin)

POST http://localhost:8080/admin/register-admin
Content-Type: application/json

{
    "firstname": "{{$dotenv FIRSTNAME}}",
    "lastname": "{{$dotenv LASTNAME}}",
    "email": "{{$dotenv ADMIN_EMAIL}}",
    "password": "{{$dotenv STRAPI_ADMIN_PASSWORD}}"
}

### 1.3 Forgot Password (Admin)

POST http://localhost:8080/admin/forgot-password
Content-Type: application/json

{
    "email": "{{$dotenv ADMIN_EMAIL}}"
}

### 1.4 Reset Password (Admin)

POST http://localhost:8080/admin/reset-password
Content-Type: application/json

{
    "resetPasswordToken": "{{$dotenv ADMIN_RESET_CODE}}",
    "password": "{{$dotenv STRAPI_ADMIN_PASSWORD}}"
}

### 1.5 Profile (Admin)

GET http://localhost:8080/admin/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzkwNDU4MDUyLCJleHAiOjE3OTMwNTAwNTJ9.j07ygxJpoZQg3Bfi1wI-_xOdr1XKhQrSkavtFXkRxZg


## 2. User Section

### 2.1 Login (User)

POST http://localhost:8080/api/auth/local
Content-Type: application/json

{
    "identifier": "kiatthikun-test61@example.com",
    "password": "Kong1122@@"
}
### 2.2 Signup (User)

POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username": "{{$dotenv USER_USERNAME}}",
    "email": "{{$dotenv USER_EMAIL}}",
    "password": "{{$dotenv USER_PASSWORD}}"
}

### 2.3 Forgot Password (User)

POST http://localhost:8080/api/auth/forgot-password
Content-Type: application/json

{
    "email": "{{$dotenv USER_EMAIL}}"
}

### 2.4 Reset Password (User)

POST http://localhost:8080/api/auth/reset-password
Content-Type: application/json

{
    "code": "{{$dotenv USER_RESET_CODE}}",
    "password": "{{$dotenv USER_PASSWORD}}",
    "passwordConfirmation": "{{$dotenv USER_PASSWORD}}"
}

### 2.5 Profile (User)

GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzkwNDU4NzU3LCJleHAiOjE3OTMwNTA3NTd9.XjFSAL11291u_gYk3-zw6Djje_2EnShwSV4LyqcNko0
## 3. Content Section

## 3.1 Student

### 3.1.1 Create Student

POST http://localhost:8080/api/students
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
  "data": {
    "name": "{{$dotenv STUDENT_NAME}}",
    "mobile": "{{$dotenv STUDENT_MOBILE}}",
    "cardId": "{{$dotenv STUDENT_CARDID}}"
  }
}
### 3.1.2 List All Students

GET http://localhost:8080/api/students
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.1.3 List Student with ID

GET http://localhost:8080/api/students/{{$dotenv STUDENT_ID}}
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.1.4 Update Student

PUT http://localhost:8080/api/students/{{$dotenv STUDENT_ID}}
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
    "data": {
        "name": "{{$dotenv STUDENT_NAME_UPDATE}}",
        "mobile": "{{$dotenv STUDENT_MOBILE_UPDATE}}",
        "cardId": "{{$dotenv STUDENT_CARDID_UPDATE}}"
    }
}


### 3.2.1 Create Subject

POST http://localhost:8080/api/subjects
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
    "data": {
        "name": "{{$dotenv SUBJECT_NAME}}"
    }
}
### 3.2.2 List All Subjects

GET http://localhost:8080/api/subjects
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.2.3 List Subject with ID

GET http://localhost:8080/api/subjects/{{$dotenv SUBJECT_ID}}
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.2.4 Update Subject

PUT http://localhost:8080/api/subjects/{{$dotenv SUBJECT_ID}}
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
    "data": {
        "name": "{{$dotenv SUBJECT_NAME_UPDATE}}"
    }
}

### 3.3.1 Create Teacher

POST http://localhost:8080/api/teachers
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
    "data": {
        "name": "{{$dotenv TEACHER_NAME}}"
    }
}
### 3.3.2 List All Teacher

GET http://localhost:8080/api/teachers
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.3.3 List Teacher with ID

GET http://localhost:8080/api/teachers/{{$dotenv TEACHER_ID}}
Authorization: Bearer {{$dotenv USER_TOKEN}}

### 3.3.4 Update Teacher

PUT http://localhost:8080/api/teachers/{{$dotenv TEACHER_ID}}
Content-Type: application/json
Authorization: Bearer {{$dotenv USER_TOKEN}}

{
    "data": {
        "name": "{{$dotenv TEACHER_NAME_UPDATE}}"
    }
}