services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54327:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-admin
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db

  app:
    build:
      context: ./strapi
    container_name: 69-s3-app
    ports:
      - "8080:1337"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: ${APP_DATABASE_CLIENT}
      DATABASE_NAME: ${APP_DATABASE_NAME}
      DATABASE_HOST: ${APP_DATABASE_HOST}
      DATABASE_PORT: ${APP_DATABASE_PORT}
      DATABASE_USERNAME: ${APP_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${STRAPI_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${STRAPI_ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${STRAPI_TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${STRAPI_JWT_SECRET}
    depends_on:
      - db
volumes:
  postgres_data:
